Content about prototyping high risk items first in principles…
axelerant/engg-handbook pull request #106
Opened 2023-09-26 23:09 UTC by Yemaneberhan-Lemma

Added content about "prototyping high risk items first" inside principles -> fundamentals page.

2023-10-06 12:51 UTC, hussainweb requested changes
@Yemaneberhan-Lemma, why do you think "Focus on Fundamentals" is the right place for this text? Especially, why is it under the section of "Working with source code"?

Looking at the other principles, maybe this is a better fit under "Focus on Engineering", IMHO. Or what do you think of introducing a new principle related to "Iterations"? cc @axelabhay

2023-10-11 07:14 UTC, axelabhay commented
> @Yemaneberhan-Lemma, why do you think "Focus on Fundamentals" is the right place for this text? Especially, why is it under the section of "Working with source code"?
> 
> Looking at the other principles, maybe this is a better fit under "Focus on Engineering", IMHO. Or what do you think of introducing a new principle related to "Iterations"? cc @axelabhay


 > Why do you think "Focus on Fundamentals"  is the right place for this text?

I think, suggestion at https://docs.google.com/document/d/1gBTKAwxjZvxTeyPtemEQbrRo5dyBhQji-tOGzw_vyXE/edit?disco=AAAA4YCsPrs has been followed. :)
 
> Especially, why is it under the section of "Working with source code"?

+1, it is `H3 heading` and falling under the section "Working with source code".

> Looking at the other principles, maybe this is a better fit under "Focus on Engineering", IMHO. Or what do you think of introducing a new principle related to "Iterations"?

The first line of this content talks about `architectural obstacles` and I think architecting is an iterative process. Yes, we can introduce "Iterations".

2023-10-11 13:04 UTC, hussainweb commented
Thanks, @axelabhay. I see I caused the confusion. Reading it now on the "Focus on Fundamentals" page seems a little weird to me. Maybe I didn't realize it earlier or I had something else in mind and have forgotten it now.

@Yemaneberhan-Lemma I think this is more related to Engineering and it might flow there. Or maybe a new page under Principles is a better choice. We can make Iterations a principle in itself and put this under there.

2023-10-11 13:25 UTC, Yemaneberhan-Lemma commented
> Thanks, @axelabhay. I see I caused the confusion. Reading it now on the "Focus on Fundamentals" page seems a little weird to me. Maybe I didn't realize it earlier or I had something else in mind and have forgotten it now.
> 
> @Yemaneberhan-Lemma I think this is more related to Engineering and it might flow there. Or maybe a new page under Principles is a better choice. We can make Iterations a principle in itself and put this under there.

@hussainweb: New page is ideal for me. And noted on creating new content/page for Iterations.

2023-10-12 12:46 UTC, hussainweb commented on content/docs/principles/prototyping-high-risk-items-first.md
> +title: Prototyping high risk items first
Let's call the page "Build in Iterations". Please change the file name too.

2023-10-12 12:47 UTC, hussainweb commented on content/docs/principles/prototyping-high-risk-items-first.md
> +weight: 1
I don't think this should be the first. Let's keep this one after "Focus on Fundamentals".

2023-10-12 12:48 UTC, hussainweb approved these changes
Nevermind, I'll merge for now and rename later during my review.

2023-10-12 12:48 UTC, merged