Added content about Drupal SEO
axelerant/engg-handbook pull request #118
Opened 2023-11-02 14:15 UTC by Yemaneberhan-Lemma

2023-11-03 20:58 UTC, hussainweb requested changes

2023-11-03 20:58 UTC, hussainweb commented on content/docs/how-we-work/drupal/drupal-seo.md
> +We configure sites that are optimized for SEO”, which improves their visibility on search engines like Google.
There is a closing double-quote after SEO. It seems like a typo.

2023-11-03 20:58 UTC, hussainweb commented on content/docs/how-we-work/drupal/drupal-seo.md
> +One of the key aspects of SEO is the use of specific modules that can enhance a site’s search engine performance. For instance, the [XML Sitemap](https://www.drupal.org/project/xmlsitemap) module cre
Yoast is another one we can mention. But please check if it still in development for Drupal.

2023-11-03 20:58 UTC, hussainweb commented on content/docs/how-we-work/drupal/drupal-seo.md
> +There are SEO practices we follow. We provide training to our clients on how to create content that is optimized for search engines. This includes using keywords effectively, writing clear and compel
Can you confirm if we actually provide training? I can’t recall if we have ever done that. If not, we can just remove that phrase and the rest of the content is fine (will just need to be rewritten to flow in a sentence).

2023-11-06 12:56 UTC, axelabhay commented on content/docs/how-we-work/drupal/drupal-seo.md
> +One of the key aspects of SEO is the use of specific modules that can enhance a site’s search engine performance. For instance, the [XML Sitemap](https://www.drupal.org/project/xmlsitemap) module cre
@Yemaneberhan-Lemma Just thought to check when we say `One of the key aspects of SEO is the use of specific modules...`, is using specific modules are the aspects of SEO? To me it sounds like using modules are the features of SEO.

2023-11-06 12:58 UTC, axelabhay commented
@Yemaneberhan-Lemma, @hussainweb, can SEO introduction participate in [Common Areas of concern with web projects](https://axelerant.github.io/engg-handbook/docs/common-areas/) page?

2023-11-09 12:24 UTC, hussainweb approved these changes

2023-11-09 12:24 UTC, merged